### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [ampotos/dynStruct#2]
looks like a nice tool, congrats!

but in the README, under "Requirement" section, Capstone is missing?

cheers.

**Comment by ampotos** [comment]
Capstone is in the requirements.txt file, I forgot to add it in the Readme.
An update of the Readme with up-to-date screenshot of the interface (with the addition of capstone disassembly) will be done tomorrow, I will add it at the same time.

**Comment by aquynh** [comment]
great! linked to your tool from our website now: http://www.capstone-engine.org/showcase.html

keep it up, cheers.

**Comment by ampotos** [comment]
Thank you for the link.
I just update the Readme.
