### ISSUE TITLE
Hello, I can't reproduct this issue, could you help me?

### ISSUE THREAD

**Issue by kEva0v0** [ampotos/dynStruct#25]
When i follow your instruction like 'drrun -c dynStruct - -- tests/test', it provide  nothing but wrong.I think it might be some wrong ways during the installing process. 
Could you upload an virtual machine image of this issue?

**Comment by kEva0v0** [comment]
`make[2]: *** No rule to make target '/home/travis/build/DynamoRIO/dynamorio/ext/drsyms/libelftc/lib32/libdwarf.a', needed by 'libdynStruct.so'.  Stop.
make[1]: *** [CMakeFiles/dynStruct.dir/all] Error 2
make: *** [all] Error 2
`
I think i got wrong in './build.sh', but i don't know why and how to fix it...

**Comment by kEva0v0** [comment]
so weird.....I build it successfully on dynStruct-linux-6.2.0, but failed on latest release version......

**Comment by kEva0v0** [comment]
i build it successfully on dynStruct-7.0.17598, but i detective nothing...
Also capstone has no X86_FP

**Comment by ampotos** [comment]
I just tested locally. Can you try with the last dynamoRIO cronbuild at https://github.com/DynamoRIO/dynamorio/releases ? I will update the README (it's working locally).

After about the detection do you see anything print ? `drrun -c dynStruct - -- tests/test` will print the block and accesses on the terminal without creating a JSON file. To use the web interface and see the structure you need the json file. 

If you want to generate this file use `drrun -c dynStruct -o <out_filename> -- tests/test`.
Then run `./dynStruct.py  -d <out_filename> -w` to load and analyse the json file and start the web interface.

Your capstone installation is not complete if you see an error message related to X86_FP (this flag is not directly used by dynStruct).

If you have any problem to have that working can you post any error message you see ?

**Comment by ampotos** [comment]
If there is no more questions about this issue I'll close it tomorrow.
